apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-jenkins-jamposik
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: jenkins-demo-dev-jamposik.exchangeweb.net
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-master-jamposik
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-jamposik
  labels:
    app: jenkins-jamposik
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: jenkins-jamposik
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-master-jamposik
spec:
  selector:
    matchLabels:
      app: jenkins-jamposik # has to match .spec.template.metadata.labels
  serviceName: "jenkins-master-jamposik"
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-jamposik  # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jamposik
        image: mshaibek/jenkins-312:latest
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: jenkinshome-jamposik
          mountPath: /var/jenkins_home
  volumeClaimTemplates:
  - metadata:
      name: jenkinshome-jamposik
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
